### ISSUE TITLE
编译后选择挑战ai，进入牌桌后左上角没有新建房间的按钮，无法开始游戏

### ISSUE THREAD

**Issue by yishui01** [dwg255/landlord#1]
![image](https://user-images.githubusercontent.com/20850040/56073614-d7b8a700-5dd9-11e9-94e4-60b39d592c71.png)

演示地址进入房间后的ws发送的数据和本地运行时的不同

![image](https://user-images.githubusercontent.com/20850040/56073665-65949200-5dda-11e9-99cc-6fe7d031ef33.png)

![image](https://user-images.githubusercontent.com/20850040/56073670-80670680-5dda-11e9-8541-9ca5c5e1811b.png)

**Comment by dwg255** [comment]
感谢反馈，看过日志了。service/table.go第135行（更新后位置）生成随机数作为robot ID的时候，因为是连续加入两个机器人，导致两次rand.Seed(time.Now().UnixNano())撒种的数是同一个，robot ID重复。在go1.11里没有出现这个问题，可能是因为go1.12运行速度更快？解决方法是在150行sleep 10微妙，如果ID重复的话重新调用此方法。再次感谢反馈

**Comment by yishui01** [comment]
好的，收到
